version: "3.7"
services:
  next:
    container_name: ntrbot-next
    image: joshkay/ntrbot-next
    restart: unless-stopped
    ports:
      - "9916:3000"
    environment:
      WHATSAPP_TRPC_URL: http://whatsapp:3333
      WHATSAPP_TRPC_PORT: 3333
      DB_USER: postgres
      DB_PASSWORD: y7FswrQHkWTSekEb
      DB_HOST: db
      DB_NAME: ntrbot
    networks:
      - ntr-bot
    # depends_on:
    #   db:
    #     condition: service_healthy

  whatsapp:
    container_name: ntrbot-whatsapp
    image: joshkay/ntrbot-whatsapp
    restart: unless-stopped
    volumes:
      - /home/josh/ntr-bot/state:/usr/src/app/whatsapp/state
    environment:
      WHATSAPP_TRPC_URL: http://whatsapp:3333
      WHATSAPP_TRPC_PORT: 3333
      DB_USER: postgres
      DB_PASSWORD: y7FswrQHkWTSekEb
      DB_HOST: db
      DB_NAME: ntrbot
      OPENAI_ORG_ID: org-av7OXkHawvIZhfHuSDOfCaNP
      OPENAI_API_KEY: sk-proj-eR6sCxdx8xi6ZBQyI1xmT3BlbkFJKdSRHE31vVt8d8dRLl15
      TZ: America/Toronto
    expose:
      - 3333
    networks:
      - ntr-bot
    # depends_on:
    #   migration:
    #     condition: service_completed_successfully

  db:
    image: postgres:15
    restart: unless-stopped
    user: postgres
    volumes:
      - /home/josh/ntr-bot/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ntrbot
      - POSTGRES_PASSWORD=y7FswrQHkWTSekEb
      - POSTGRES_USER=postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ntr-bot

  # migration:
  #   build:
  #     context: ./db
  #     additional_contexts:
  #       root: ./
  #   environment:
  #     DB_USER: postgres
  #     DB_PASSWORD: y7FswrQHkWTSekEb
  #     DB_HOST: db
  #     DB_NAME: ntrbot
  #   networks:
  #     - ntr-bot
  #   depends_on:
  #     db:
  #       condition: service_healthy

networks:
  ntr-bot:
