name: Build Next.js Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  docker-next:
    runs-on: ubuntu-latest
    env:
      CONTEXT_SUBDIR: next
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./next
          build-contexts: |
            root=./
          push: true
          tags: joshkay/ntrbot-next:latest
  docker-whatsapp:
    runs-on: ubuntu-latest
    env:
      CONTEXT_SUBDIR: whatsapp
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./whatsapp
          build-contexts: |
            root=./
          push: true
          tags: joshkay/ntrbot-whatsapp:latest
